name: S3 deploy action
description: 'This action is to perform deployment to S3'

inputs:
  BUCKET_NAME:
    description: 'Name of the bucket on which we want to deploy'
    required: true
  PATH:
    description: 'path of folder or file to be deployed'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: s3 deploy action
      run: aws s3 sync ${{ inputs.PATH }} s3://${{ inputs.BUCKET_NAME }} --delete
      shell: bash
    - name: Cloudfront invalidation
      run: |
        export BUCKET_REGION=`aws s3api get-bucket-location --bucket backup-bucket-manthan --query 'LocationConstraint' --output text`
        if [ ${{ inputs.create_distribution }} == true ]; then
        export DOMAIN_NAME=${{ inputs.BUCKET_NAME }}.s3.$BUCKET_REGION.amazonaws.com
        export REFERENCE_DOMAIN=`aws cloudfront list-distributions --query "DistributionList.Items[*].Origins.Items[*].Id" --output text`
          if [$REFERENCE_DOMAIN != $DOMAIN_NAME]; then
        export DISTRIBUTION_ID=`aws cloudfront create-distribution --origin-domain-name  ${{ inputs.BUCKET_NAME }}.s3.$BUCKET_REGION.amazonaws.com --default-root-object index.html --query 'Distribution.Id' --output text`
        aws cloudfront create-invalidation --distribution-id ${{ inputs.DISTRIBUTION_ID }} --paths "/*"
      shell: bash