name: Lambda deploy action
description: 'This action is to perform lambda deployment'

inputs:
 DIR_PATH:
    description: 'path of folder to be zipped'
    required: true
 FUNCTION_NAME:
    description: 'Name of Lambda Function'
    required: true
 BUCKET_NAME:
    description: 'Name of Bucket'
    required: true
 FUNCTION_ZIP_FILE: 
    description: 'Name of zip file'
    required: true
    
runs:
  using: "composite"
  steps:
      - name: zip the function folder
        run: zip -r ${{ inputs.FUNCTION_ZIP_FILE }} ${{ inputs.DIR_PATH }}
        shell: bash
       
      - name: Upload function zip file to S3
        run: aws s3 cp ${{ inputs.ZIP_FILE }} s3://${{ inputs.BUCKET_NAME }}/${{ inputs.FUNCTION_ZIP_FILE }}

      - name: Update lambda function code
        run: aws lambda update-function-code --function-name ${{ inputs.FUNCTION_NAME }} --s3-bucket ${{ inputs.BUCKET_NAME }} ${{ inputs.FUNCTION_ZIP_FILE }}
        
#       - name: Test the function
#         run: aws lambda invoke --function-name ${{ inputs.FUNCTION_NAME }} output.json     
