name: Docker build action
description: 'This action is to perform docker build command for building image'

inputs:
  file_location:
    description: 'File path of Dockerfile'
    required: false
    default: .
  app_name:
    description: 'Dockerfile name'
    required: true
    default: myapp
  image_tag:
    description: 'Tag for image to build'
    required: true
    default: latest
  image_version:
    description: 'Additional tag for the image'
    required: false
    default: v1
  build_argument:
    description: 'Build argument key'
    required: false
    default: npm_token
  argument_value:
    description: 'Build argument value'
    required: false
    default: 'dasdsadasd'
  container_registry:
    description: 'container registry'
    default: 'registry.hub.docker.com'
    required: false
  repository_name:
    description: 'Repository name to push image to'
    required: true
    default: 'test'
runs:
  using: "composite"
  steps:
    - name: Docker build actions
      run: docker build -t ${{ inputs.app_name }}:${{ inputs.image_tag }} -t ${{ inputs.app_name }}:${{ inputs.image_version }} -t ${{ inputs.app_name }}:${{ inputs.container_registry }}/${{ inputs.repository_name }} --build-arg ${{ inputs.build_argument }}=${{ inputs.argument_value }} ${{ inputs.file_location }}
      shell: bash
    - name:  Push image to docker
      run: docker push --all-tags ${{ inputs.container_registry }}/${{ inputs.repository_name }}
      shell: bash
    
